### ISSUE TITLE
🧐[问题]antd-style写的样式，无法覆盖antd组件(:where)样式，有什么写法可以覆盖吗?

### ISSUE THREAD

**Issue by luyuanx2** [ant-design/antd-style#100]
### 🚑 其他信息

<img width="535" alt="image" src="https://github.com/ant-design/antd-style/assets/26129033/a7d33502-170b-420d-a4ff-9060a93b7c1c">

**Comment by arvinxx** [comment]
这个就是常规的优先级踩踏的问题， .ant-layout .ant-layout-sider 优先级有两层… 和 where 没啥关系…

**Comment by arvinxx** [comment]
参见：https://github.com/ant-design/antd-style/issues/24
