### ISSUE TITLE
👑 [需求] 现在默认的 `DEFAULT_CSS_PREFIX_KEY` 是  `acss`，有没有可能设定为 `__filename__` /  `__classname__` 然后再加上 hash？

### ISSUE THREAD

**Issue by SolidZORO** [ant-design/antd-style#102]
### 🥰 需求描述

现在默认的 `DEFAULT_CSS_PREFIX_KEY` 是  `acss`，有没有可能设定为 `__filename__` /  `__classname__` 这种，然后再加上 hash？

因为开发过程种发现，目前只靠 `acss-xxxx` 对定位并不友好，较难找到源码中的相对 classname。

**Comment by arvinxx** [comment]
详见：https://ant-design.github.io/antd-style/guide/babel-plugin

**Comment by FontEndArt** [comment]
> 详见：https://ant-design.github.io/antd-style/guide/babel-plugin

真的就不考虑不适用babel的技术栈了么。。。虽然现在能用StyleProvider实现，但是需要额外包裹一层，确实挺麻烦还是

**Comment by arvinxx** [comment]
@FontEndArt 具体展开下？ StyleProvider实现又咋实现？

**Comment by FontEndArt** [comment]
> @FontEndArt 具体展开下？ StyleProvider实现又咋实现？

对不起，我的错，刚开始使用，研究不全面。
`<StyleProvider prefix="footer"><FooterFC /></StyleProvider>`
我在使用过程中发现这样是可以生效的，然后我就将其封装成了一个高阶函数，写组件的时候顺带包裹一下，并且传入该组件对应的prefix。

但是我再又一遍浏览文档的过程中，发现createInstance可以实现相同需求。准备让全部组件都改用createInstance来定义。

核心需求只是为了在调试的时候可以方便找到这个组件而已（新人友好型），之前在看https://github.com/lobehub/lobe-chat这个仓库的时候，本地运行起来找组件对应关系的时候还是挺费劲的，几乎都是默认的prefix，相比之下我个人可能更喜欢classnames提供的hash模式（ps:也许之前用习惯了antd@5-）。

**Comment by senro** [comment]
具体怎么实现的啊？大神，现在这个无法定位类名的问题感觉很麻烦啊

**Comment by starplatinum3** [comment]
各位佬,这种行为应该得是antd-style的默认行为吧,竟然还要搞麻烦的配置,antd-style可以帮忙做成默认配置吗
