### ISSUE TITLE
🐛[BUG]umijs4中增加antd-style报错

### ISSUE THREAD

**Issue by yangjiaqiao** [ant-design/antd-style#118]
### 🐛 bug 描述
在umijs4增加antd-style后，进行样式创建，使用时报错。
样式代码：
![image](https://github.com/ant-design/antd-style/assets/51978469/0da7af05-06df-48f0-a2af-2d54a456befa)
使用样式代码：
![image](https://github.com/ant-design/antd-style/assets/51978469/9b4528e5-a7cc-440e-826b-09384eb4e599)
报错信息：
![image](https://github.com/ant-design/antd-style/assets/51978469/cb9b66f2-59af-47f4-a6d9-053b10eeef57)

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/html2ksetch-demo-m53be?file=/src/Demo.tsx)

### © 版本信息

- antd-style 版本: [3.5.0]
- antd 版本: [5.10.2]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by arvinxx** [comment]
清理下 MFSU的缓存，然后再试试？

**Comment by yangjiaqiao** [comment]
清除了也是同样的错误

**Comment by yangjiaqiao** [comment]
> 清理下 MFSU的缓存，然后再试试？

清除了也是同样的错误

**Comment by arvinxx** [comment]
给个复现 demo ？

**Comment by yangjiaqiao** [comment]
> 给个复现 demo ？
现在的问题是，在第一次渲染的时候会保存，但是当编辑其中任何代码保存后，热更新后就不回报错了

**Comment by arvinxx** [comment]
是不是你的react环境有问题？

**Comment by yangjiaqiao** [comment]
> 是不是你的react环境有问题？
你好，谢谢！找到问题了，是我采用的umi4搭建的，但是针对“mfsu”并没有指定策略，加上
` mfsu: {
    strategy: 'normal',
  }`
  就可以了。
但是具体的原因还是有些不是很明白.
