### ISSUE TITLE
👑 [需求] 能否不依赖 antd 

### ISSUE THREAD

**Issue by 1021683053** [ant-design/antd-style#127]
### 🥰 需求描述

能否把antd的theme作为参数传入，而不是依赖于antd的theme。这样这个库就可以给别的系统使用。

![image](https://github.com/ant-design/antd-style/assets/7711802/b245f9e8-e5ce-421a-a0f8-ff5c8f0fd519)

**Comment by arvinxx** [comment]
我个人现在没有精力和兴趣做一个独立的样式引擎解决方案。

@MadCcc  考不考虑下抽一个独立样式引擎方案出来？比如完全剥离掉 emotion，换成 `ant-design/cssinjs` 。然后 antd-style 基于这个引擎方案基础上再加 antd token 封装。
