### ISSUE TITLE
🐛[BUG] createStyles token ts 提示有问题

### ISSUE THREAD

**Issue by DaphnisLi** [ant-design/antd-style#134]
"antd-style": "^3.4.4"

如图，primaryColor 提示不存在是否合理？如果是我的问题，那么正确写法应该是如何的？
![image](https://github.com/ant-design/antd-style/assets/67792799/14de4332-13cf-4607-8e7e-74f73ba67c2a)
![image](https://github.com/ant-design/antd-style/assets/67792799/9bf10d69-5838-4c42-a31d-3d37f6b9769c)

**Comment by arvinxx** [comment]
应该是写法问题。 看下这个 https://ant-design.github.io/antd-style/api/theme-provider#typescript-type-support

**Comment by DaphnisLi** [comment]
> 应该是写法问题。看下这个https://ant-design.github.io/antd-style/api/theme-provider#typescript-type-support

这里的症状是 token 只是 ts 报错，还是可以正常生效的。
我的 createStyles 是从 createInstance 拿来的，按理说应该将 createStyles 里的 token 类型扩展一下。

**Comment by DaphnisLi** [comment]
> > 应该是写法问题。看下这个https://ant-design.github.io/antd-style/api/theme-provider#typescript-type-support
> 
> 这里的症状是 token 只是 ts 报错，还是可以正常生效的。 我的 createStyles 是从 createInstance 拿来的，按理说应该将 createStyles 里的 token 类型扩展一下。

@arvinxx

**Comment by arvinxx** [comment]
> > 应该是写法问题。看下这个https://ant-design.github.io/antd-style/api/theme-provider#typescript-type-support
> 
> 这里的症状是 token 只是 ts 报错，还是可以正常生效的。 我的 createStyles 是从 createInstance 拿来的，按理说应该将 createStyles 里的 token 类型扩展一下。

对，目前可能需要你手动扩展下。在 createInstance 自动集成这个感觉需要额外实现一下相关的类型能力
