### ISSUE TITLE
Typography.Text 样式闪烁

### ISSUE THREAD

**Issue by Vsion** [ant-design/antd-style#136]
### 🧐 问题描述
![image](https://github.com/ant-design/antd-style/assets/11804448/4fd98a41-407f-4e31-8d2e-d30d3d657865)
每次刷新的时候 
`
<Typography.Text ellipsis>{user.name}</Typography.Text>
`
闪一下再正常
![image](https://github.com/ant-design/antd-style/assets/11804448/7d4f2f4a-464d-490c-aedd-df8a2583e61e)
感觉是这行 classname 加载的问题, 

`
    "antd": "^5.12.6",
    "antd-mobile": "^5.34.0",
    "antd-style": "^3.6.1",
    "next": "14.0.4",
`

**Comment by Vsion** [comment]
![image](https://github.com/ant-design/antd-style/assets/11804448/05cd1fd8-e45d-43f0-af15-b6f7b1fe45f5)
去掉这个类名之后和第一张图现象一样

**Comment by arvinxx** [comment]
这个和 antd-style 有啥关系？
