### ISSUE TITLE
🐛[BUG]nextjs app router，createStyles在服务端未生成style标签导致页面闪烁。

### ISSUE THREAD

**Issue by yqz0203** [ant-design/antd-style#138]
### 🐛 bug 描述

使用antd + nextjs app router，根据官方配置了`AntdRegistry`, 但单独使用ant-style的`createStyles`在服务端未生成<style>导致页面闪烁，而antd的组件的样式是正常渲染的。

style是在客户端渲染后插入的，服务端未返回
<img width="407" alt="image" src="https://github.com/ant-design/antd-style/assets/8850879/5f10fab3-9a72-485a-8843-f6eb8da45805">

### 📷 复现步骤

1. 按照官方教程启动antd+nextjs
2. 使用createStyles创建自定义样式

### 🏞 期望结果

`createStyles` 创建的样式能在服务端渲染阶段正常提取和返回。

### 💻 复现代码
``` typescript
const useStyles = createStyles(({ token }) => {
  return {
    item: {
      height: 45,
      borderBottom: 'solid 1px',
      borderBottomColor: token.colorBorderSecondary,
      '&:hover': {
        background: token.colorBgTextHover,
      },
    },
  };
});

function Item({ name }: { name: string }) {
  const { styles } = useStyles();
  return (
    <Row align="middle" className={styles.item} gutter={8}>
      <Col span={10}>{name}</Col>
      <Col span={4}>20</Col>
      <Col span={4}>10</Col>
      <Col span={6} style={{ textAlign: 'right' }}>
        <Button size="small" type="primary">
          挂号
        </Button>
      </Col>
    </Row>
  );
}
```

### © 版本信息

- antd-style 版本:  3.6.1
- 浏览器环境 : edge 最新版 
- 开发环境  mac OS

### 🚑 其他信息

服务端渲染：

<img width="396" alt="image" src="https://github.com/ant-design/antd-style/assets/8850879/0959f5d5-bb3d-47b4-a42e-8f4b4c400e57">

客户端渲染后：

<img width="383" alt="image" src="https://github.com/ant-design/antd-style/assets/8850879/91fe4d30-12fe-4c6c-8728-8b9304331cc6">

**Comment by yqz0203** [comment]
解决了，AntdRegistry集成的是`@antdesign/cssinjs`。ant-style还要单独集成一遍。

晕死，为啥要搞2套cssinjs哦？😓

**Comment by arvinxx** [comment]
https://ant-design.github.io/antd-style/guide/ssr#app-router

**Comment by yqz0203** [comment]
@arvinxx 请问下，antd为什么不直接用ant-style作为底层呢。@ant-design/cssinjs最大的问题是没有提供自定义复杂样式的能力，useToken遇到hover之类的需求就哑火了。个人感觉antd应该像mui一样内置整套样式方案😂

**Comment by arvinxx** [comment]
> antd为什么不直接用ant-style作为底层呢。

因为 antd-style 的性能没有 @ant-design/cssinjs 高。组件级的 cssinjs 实现逻辑和业务的实现逻辑不完全一致。详细介绍可以看这里：https://ant-design.antgroup.com/docs/blog/css-in-js-cn

> @ant-design/cssinjs最大的问题是没有提供自定义复杂样式的能力

不是不支持，而是你要用这个放方案写样式会麻烦死…这个方案是为了解决以前 cssinjs 遇到的性能问题而为组件库量身定制的解决方案，但放到业务场景里不合适。

mui 从组件到应用都一样用一套，最后的社区反馈就是卡…
