### ISSUE TITLE
👑 [需求]在nextjs中样式提取到静态文件

### ISSUE THREAD

**Issue by Ryuurock** [ant-design/antd-style#139]
### 🥰 需求描述
期望在构建时能一同提取样式到静态文件，减少html的体积

### 🧐 解决方案
能够像antd一样使用@ant-design/static-style-extract 进行样式提取

**Comment by arvinxx** [comment]
标准解决方案是这个：https://ant-design.github.io/antd-style/zh-CN/guide/ssr

提取成静态文件不适用于 nextjs
