### ISSUE TITLE
二次封装antd5.0，并希望能在调用方使用token改变样式，应该怎么写样式

### ISSUE THREAD

**Issue by qc-z** [ant-design/antd-style#14]

**Comment by arvinxx** [comment]
会有的

**Comment by qc-z** [comment]
> 会有的

有方案吗？

**Comment by qc-z** [comment]
目前使用v5遇到的难点
1 我们的组件库是二次封装v5的，用v4那套修改样式的话，在调用方使用ConfigProvider进行动态主题时候，where选择器无法覆盖二次封装的样式
2 二次封装的样式也希望通过ConfigProvider这个来动态修改主题
感谢大佬~

**Comment by arvinxx** [comment]
@qc-z  查阅最新的组件研发部分文档：https://ant-design-antd-style-preview-pr-19.surge.sh/guide/components-usage
