### ISSUE TITLE
🧐[问题]Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by Amazing-0921** [ant-design/antd-style#141]
TypeError: Cannot read properties of null (reading 'useContext')
![image](https://github.com/ant-design/antd-style/assets/68459563/d6c5f0de-b125-4a9e-93a3-0d935d7938ba)

**Comment by arvinxx** [comment]
你的React相关依赖是不是配置得不对

**Comment by Amazing-0921** [comment]
![image](https://github.com/ant-design/antd-style/assets/68459563/749740f4-72d9-4ad5-a9c3-86961d7df8ac)
上午改成功了，下午又出现了

**Comment by Amazing-0921** [comment]
大师，我该怎么整

**Comment by arvinxx** [comment]
@Amazing-0921 

1. 试一试清理依赖和缓存（删node_modules）；
2. 如果不行，试试关闭 mfsu

**Comment by Amazing-0921** [comment]
删除 node_modules不行，关闭 mfsu 后可以，谢谢大师

**Comment by arvinxx** [comment]
那应该是 react 多实例的问题… 你找找umi文档里关于 mfsu 的部分看看，我记得有相关进一步配置介绍的

**Comment by Amazing-0921** [comment]
mfsu: {
  shared: {
    react: {
      singleton: true,
    },
  },
},

换成 umi 文档里的配置阔以
