### ISSUE TITLE
🧐[问题]怎么修改像 Drawer， message 这种存在 rootClassName 的组件的样式

### ISSUE THREAD

**Issue by wangchaoHeart** [ant-design/antd-style#153]

**Comment by arvinxx** [comment]
没区别啊，直接写就好了

**Comment by wangchaoHeart** [comment]
根本不行， 假如我们现在要修改 antd组件Dropdown下来选项的选中样式，我们可以发现下拉选项是渲染在下图1的位置，我们根本没法用class选中它，没法修改
![image](https://github.com/ant-design/antd-style/assets/117444298/2f662a68-1894-431f-9193-0a66406e2185)

**Comment by wangchaoHeart** [comment]
![image](https://github.com/ant-design/antd-style/assets/117444298/2c492d13-9039-4b56-8405-186e89026c71)
我的需求就是  修改Table表头的过滤下拉框的样式，根本改不了

**Comment by arvinxx** [comment]
不是有popupClassname 么？挂那个啊

**Comment by wangchaoHeart** [comment]
> 不是有popupClassname 么？挂那个啊
Table上的默认过滤弹框怎么挂载？ 重写他的过滤弹框吗？
![image](https://github.com/ant-design/antd-style/assets/117444298/e5df6e03-44fb-489d-96a0-e6540a26d447)

**Comment by arvinxx** [comment]
这个你去看下 Table 有没有给出这个 className ？ 和 antd-style 似乎没啥关系。

**Comment by wangchaoHeart** [comment]
antd-style 库的作用 是在js中写css  怎么会没关系那？

**Comment by arvinxx** [comment]
@wangchaoHeart 如果 Table 这个 filter 面板，antd 本身也没有给出 className ，那么你用其他 css 方案（less 、 scss） 不是也没法覆写么？

**Comment by wangchaoHeart** [comment]
Table的filter面板有classname，其他css方案（less等）可以直接写样式覆盖antd的样式。
但是antd-style不行，antd-style必须挂载到一个dom元素上，且只能修改这个元素和子元素的样式，但是Table的filter面板是渲染在顶层的，所以没法修改

**Comment by wangchaoHeart** [comment]
![Screenshot_2024-06-20-22-12-33-479_com.android.browser.jpg](https://github.com/ant-design/antd-style/assets/117444298/7dbe68eb-f4a8-4890-bdca-855e797352a3)
就如同我截图一样，Table是渲染在2中的，但是当你打开Table的filter面板，你会发现面板是渲染在1中的，所以antd-style写的样式不生效

**Comment by wangchaoHeart** [comment]
不知道我描述的是否清清晰，是否需要我搞一个在线代码？

**Comment by wangchaoHeart** [comment]
> > Table的filter面板有classname，其他css方案（less等）可以直接写样式覆盖antd的样式。
> 
> 其他样式方案如果用css modules 不一样得挂到某个 className 上吗？如果不挂到某个className ，就要用全局作用域的覆写。在antd-style 里你要用全局覆写的话可以用 createGlobalStyle 呗

太感谢了，终于解决了我的问题, 我要找的就是全局覆盖的写法，经测试 createGlobalStyle可以解决我的需求
