### ISSUE TITLE
🧐[问题] 公司内部 fork 的 antd@3 版本能用这个吗？

### ISSUE THREAD

**Issue by warmhug** [ant-design/antd-style#156]
### 🧐 问题描述

想基于 https://github.com/ant-design/pro-components  fork 一份代码，但需要替换底层的 antd@5 为内部 fork 的 antd@3 版本。内部系统升级比较困难，比如从 antd@3 - @5 有没有平滑简单的方案？
antd-style 必须和 antd@5 版本搭配吗？能否和 @3 搭配？

**Comment by arvinxx** [comment]
不能和 @3 搭配
