### ISSUE TITLE
🐛[BUG]“ThemeProvider”不能用作 JSX 组件

### ISSUE THREAD

**Issue by xiongquanshun** [ant-design/antd-style#157]
### 💻 复现代码

[可复现 demo](https://codesandbox.io/p/sandbox/smoosh-darkness-67jskq?file=%2Fpackage.json%3A53%2C1)

### © 版本信息
- antd-style 版本: [e.g. 5.18.3]
- 浏览器环境
- react: ^18.3.1
- @types/react: ^18.3.3
- antd-style: ^3.6.2
- 开发环境 [e.g. window]

**Comment by arvinxx** [comment]
fix https://github.com/ant-design/antd-style/issues/98

**Comment by xiongquanshun** [comment]
> fix #98
我这边版本也是18+的，但好像不行

**Comment by Lliuxs** [comment]
为什么直接给关了？
