### ISSUE TITLE
🧐[问题] 请问一下如何给antd-style 扩展 CustomToken 对象类型定义

### ISSUE THREAD

**Issue by qc-z** [ant-design/antd-style#16]
### 🧐 问题描述

按照作者的文档写了如下代码

### 💻 示例代码

![image](https://user-images.githubusercontent.com/22362903/219262943-c71ffec9-9f2a-483d-b732-ec6443ec7f21.png)
报错如下
![image](https://user-images.githubusercontent.com/22362903/219262985-d44d5152-bf77-4c29-89d5-9d056579a1b0.png)
### 🚑 其他信息

我在每个组件里面都这样子定义，请问这是错误的写法吗

**Comment by arvinxx** [comment]
不能用type 需要用interface

**Comment by arvinxx** [comment]
已在文档中补充，[commit](https://github.com/ant-design/antd-style/commit/b394d9e9cdac7dd27df31463b808337586a00409)
