### ISSUE TITLE
🧐[问题]vscode的自动补全问题无法正常显示

### ISSUE THREAD

**Issue by panjunqiu** [ant-design/antd-style#166]
### 🧐 问题描述

之前的项目可以正常自动提示，最新新的项目升级了一些依赖后无法自动提示，没中到问题。

* 正常情况： 
<img width="812" alt="image" src="https://github.com/user-attachments/assets/96da5d09-5ca4-4a8c-aaec-1055437cf1ed">

* 异常情况：
<img width="749" alt="image" src="https://github.com/user-attachments/assets/fa93d09f-794e-4e5e-b76f-99eb3d811a4b">

### 已安装了插件
vscode-styled-components

**Comment by liuweiGL** [comment]
这个 [commit ](https://github.com/ant-design/antd-style/commit/3ccd27d1223e3b2a1bb639aa0537235ac41c0ac0) 升级了 `@emotion/css` 版本:
![image](https://github.com/user-attachments/assets/2e7f41b0-7a4a-4acc-921c-c1028493717f)
而 11.13 版本不再导出 CSSObject 类型，所以从 https://github.com/ant-design/antd-style/blob/master/src/types/css.ts#L7  这里开始 CSSObject 类型就是 unknown 了
