### ISSUE TITLE
🧐[问题]什么不是直接定义主题影响antd默认风格，而要在代码里面嵌入一堆style

### ISSUE THREAD

**Issue by coyzeng** [ant-design/antd-style#168]

**Comment by coyzeng** [comment]
为什么不是直接定义主题影响antd默认风格，而要在代码里面嵌入一堆style

**Comment by arvinxx** [comment]
没懂啥意思

**Comment by coyzeng** [comment]
> 没懂啥意思

不是开箱即用的，类似于引入antd-style之后，ThemeProvider提供开箱即用的theme，不需要在element上写style。开发者需要定制的时候才通过几种途径去定制css：
1、themeconfig
2、cssinjs

**Comment by arvinxx** [comment]
你说的应该是主题包。主题包不是 antd-style 该做的事情。antd-style 对标的是 Styled Components 这样的样式库，你也没见 Styled 有给什么主题吧
