### ISSUE TITLE
🧐和https://github.com/ant-design/cssinjs 的区别？

### ISSUE THREAD

**Issue by vscing** [ant-design/antd-style#18]
🧐和https://github.com/ant-design/cssinjs 的区别？

**Comment by arvinxx** [comment]
`@ant-design/cssinjs` 是 antd 实现自己组件库的一套 cssinjs 库，它通过比较繁琐的写法换得了相比 styled-component 和 emotion 都要好很多的性能。详见：[组件级别的 CSS-in-JS](https://ant.design/docs/blog/css-in-js-cn)。但对应用和基于antd封装的组件库中，大概率是无法接受这种繁琐写法的。

所以 antd-style 是面向业务应用和基于 antd 二次封装的组件库，所提供的 cssinjs 研发解决方案。

**Comment by vscing** [comment]
@ant-design/cssinjs确实很繁琐，，老哥你这个 antd-style是后期官方推荐的业务组件样式标准还是kpi工具。。

**Comment by vscing** [comment]
@arvinxx

**Comment by arvinxx** [comment]
是官方推荐。另外这个库都不在我的kpi里，🤫用爱发电
