### ISSUE TITLE
🧐[问题]Webstorm里报类型错误警告能解决吗？

### ISSUE THREAD

**Issue by shedan9** [ant-design/antd-style#180]
### 🧐 问题描述
Webstorm里类型提示出错，虽然不影响运行，但是总有一根屎黄色警告线，作为有代码洁癖的人看着很不顺眼

<img width="821" alt="image" src="https://github.com/user-attachments/assets/f70feb32-eeda-48e8-9e5b-682fd2996c54">

**Comment by arvinxx** [comment]
Ts 哪个版本？正常来说不会有报错的

**Comment by arvinxx** [comment]
Ts 哪个版本？正常来说不会有报错的

**Comment by shedan9** [comment]
> Ts 哪个版本？正常来说不会有报错的

项目装的TS版本是4.9.4

**Comment by arvinxx** [comment]
@shedan9 太老了，升级到 v5 就不会报错了。
