### ISSUE TITLE
👑 className精准定位

### ISSUE THREAD

**Issue by vscing** [ant-design/antd-style#22]
### 🥰 需求描述
当我写完一个样式，我去dom节点查找的时候，无法精准的知道样式加在那个元素上了。全部都是class=“ant-css-XXXX”

**Comment by arvinxx** [comment]
这个需要 babel 插件配合，现在还没做，但这个功能我们之前是有规划的，正式版发布前会准备好

**Comment by vscing** [comment]
> babel 插件
正式版本什么时候发布啊？

**Comment by arvinxx** [comment]
Beta半个月左右，rc再半个月左右。正式版差不多3月底

**Comment by chj-damon** [comment]
现在已经5月底了

**Comment by arvinxx** [comment]
计划赶不上变化🤣 正式版已经发了。而且还有了less转cssinjs 的codemod，但这个还没实现

**Comment by arvinxx** [comment]
@vscing @chj-damon 已支持，详见：https://ant-design.github.io/antd-style/guide/babel-plugin

**Comment by wjf40390** [comment]
其实我想要的是样式加在哪个元素上了，例如下面的代码，希望className包含layout或者container字样这样更加容易区分，插件提供的className 将会定位到对应的样式文件目录感觉没太大用处。
<img width="537" alt="image" src="https://github.com/ant-design/antd-style/assets/41931794/3269fb81-48b9-4f62-b5b9-0d97c766d3e6">

**Comment by chj-damon** [comment]
目前babel插件确实看不出来是哪个样式。
