### ISSUE TITLE
👑 样式权重问题

### ISSUE THREAD

**Issue by vscing** [ant-design/antd-style#24]
### 🥰 需求描述
 样式权重会被antd样式覆盖，有相关权重提升方案吗？

**Comment by arvinxx** [comment]
给个case？

**Comment by vscing** [comment]
[demo](https://codesandbox.io/embed/keen-panna-4mg6h9?fontsize=14&hidenavigation=1&theme=dark)

这个只能这样强制覆盖写吗？

![image](https://user-images.githubusercontent.com/20698627/221071510-a6762617-a6e7-4a3a-b1b9-b93b70b4d002.png)


“新组件书写方案” 文档我看没写？我是直接拉的代码本地起的文档服务
![image](https://user-images.githubusercontent.com/20698627/221071546-3d365746-000d-47dc-a6a4-ce520118db90.png)

**Comment by arvinxx** [comment]
@vscing 如果只是 layout 的话，看下这个讨论：https://github.com/ant-design/ant-design/discussions/40879

> “新组件书写方案” 文档我看没写？

还没写

**Comment by vscing** [comment]
> @vscing 如果只是 layout 的话，看下这个讨论：[ant-design/ant-design#40879](https://github.com/ant-design/ant-design/discussions/40879)
> 
> > “新组件书写方案” 文档我看没写？
> 
> 还没写

有方案或者构思了吗？钉钉群有吗？项目在使用了。

**Comment by vscing** [comment]
那我现在只能在layout定义一个样式，里面包含header上的className。或者是强制覆盖、再或者就类似迁移less 一样，直接return 一个 css``。感觉有点懵

**Comment by vscing** [comment]
那我现在只能在layout定义一个样式，里面包含header上的className。或者是强制覆盖、再或者就类似迁移less 一样，直接return 一个 css``。感觉有点懵

**Comment by arvinxx** [comment]
> 有方案或者构思了吗？钉钉群有吗？项目在使用了。


用createInstance

**Comment by arvinxx** [comment]
> 那我现在只能在layout定义一个样式，里面包含header上的className。或者是强制覆盖、再或者就类似迁移less 一样，直接return 一个 css``。感觉有点懵

目前看就是要覆盖样式的。

**Comment by arvinxx** [comment]
@vscing 看了下你的 demo，覆盖是覆盖，但写法有更好的：https://codesandbox.io/s/determined-dan-sw3wb7?file=/style.ts

**Comment by vscing** [comment]
666
