### ISSUE TITLE
🐛[BUG] 使用createInstance，传入customToken默认值，在外层调用ThemeProvider会全量覆盖

### ISSUE THREAD

**Issue by qc-z** [ant-design/antd-style#25]
### 🏞 期望结果
有就覆盖，没有就使用默认

**Comment by arvinxx** [comment]
收到 是个bug 今天修一下

**Comment by arvinxx** [comment]
fixed in [3.0.0-beta.7](https://github.com/ant-design/antd-style/releases/tag/v3.0.0-beta.7)

**Comment by kevinffk** [comment]
看起来确实是被全量覆盖了，我本地的版本是3.2.1的  https://github.com/ant-design/antd-style/issues/69
