### ISSUE TITLE
🧐[问题] next.js应该怎么使用？

### ISSUE THREAD

**Issue by mwj610** [ant-design/antd-style#30]
https://ant-design-antd-style-preview-pr-19.surge.sh/guide/ssr

<img width="963" alt="image" src="https://user-images.githubusercontent.com/52907799/222935586-7b332bfd-5c06-4c0a-9470-92a9e401d8ee.png">

**Comment by arvinxx** [comment]
给个示例仓库？nextjs 还没试过

**Comment by mwj610** [comment]
> 给个示例仓库？nextjs 还没试过

不好意思，是antd的InputNumber的问题
