### ISSUE TITLE
请教一个问题，路由切换当从/about切换到/user，页面就会闪动

### ISSUE THREAD

**Issue by vscing** [ant-design/antd-style#32]
### 🧐 问题描述
使用react-router v6，路由用的懒加载，第一次/about切到/user就会闪动，再来回切正常。这个你知道有解决方案吗？

**Comment by arvinxx** [comment]
有示例么？或者录屏

**Comment by vscing** [comment]
![闪屏](https://user-images.githubusercontent.com/20698627/223924314-8a697527-cf1a-48b8-ad77-b69468cbf8c4.gif)

**Comment by vscing** [comment]
![闪屏](https://user-images.githubusercontent.com/20698627/223925416-dea98714-0fdc-4925-af00-65b79675869e.gif)

**Comment by vscing** [comment]
react 18 导致 antd 菜单折叠时闪烁

**Comment by vscing** [comment]
> react 18 导致 antd 菜单折叠时闪烁

这个问题官方还没修复吗？

**Comment by vscing** [comment]
还有modal组件，主题样式没有作用到上面，是不是要设置挂载节点？

**Comment by xyunsh** [comment]
是不是使用了lazy load
