### ISSUE TITLE
antd-style是基于 emotion 二次封装的，我想知道antd-style会像@ant-design/cssinjs一样有更好的性能吗？

### ISSUE THREAD

**Issue by wyl199** [ant-design/antd-style#35]
antd-style会像@ant-design/cssinjs一样带来更好的性能吗

**Comment by arvinxx** [comment]
达不到cssinjs包这个水平，原因是cssinjs包在不支持响应props的设定下可以静态化，进而提升性能。但业务应用中需要使用props来动态响应样式，所以这一点是比不上的原因。

但 antd-style 的整体性能会比裸用emotion react 或者emotion css好。毛估估和 styled 应该差不多。具体还没做性能测试。

**Comment by arvinxx** [comment]
你可以体感对比一下antd-style的文档站点和antd 官网的站点。antd-style的文章站点样式就是自己吃狗粮，antd 官网的是用的emotion

**Comment by arvinxx** [comment]
实测下来，性能应该是在 CSSinJS 库的第一梯队

<img width="1002" alt="image" src="https://github.com/ant-design/antd-style/assets/28616219/321ae01f-dff8-4ae1-8ba2-b7328d4fb4f3">
