### ISSUE TITLE
🧐[使用ThemeProvider方法报错]

### ISSUE THREAD

**Issue by resetsix** [ant-design/antd-style#36]
### 🧐 问题描述

使用【create-react-app antd-demo --template typescript】命令安装"antd": "^5.3.2","antd-style": "3.0.0-beta.19",这两个版本依赖包后，想要用【import { ThemeProvider } from "antd-style";】的ThemeProvider方法修改全局样式，但是yarn start后直接提示webpack插件报错，试过很多次，也换过浏览器都不行。没有动过其他地方代码。yarn，pnpm都试过还是没办法。求解决

### 💻 示例代码

![image](https://user-images.githubusercontent.com/85431995/227510610-6732c4ed-0e75-48dd-aefe-945dc2b67d25.png)

### 🚑 报错截图

![微信截图_20230324193131](https://user-images.githubusercontent.com/85431995/227510392-8ba268fc-ea4d-4f07-9394-3ed1cb84605e.png)

**Comment by resetsix** [comment]
![image](https://user-images.githubusercontent.com/85431995/227511148-d375b703-2fb1-43c5-8b62-3b0b3dc28d06.png)
是版本问题吗还是什么？

**Comment by arvinxx** [comment]
这个和antd-style有关系吗

**Comment by resetsix** [comment]
> 这个和antd-style有关系吗

使用ThemeProvider 改默认样式启动就报错，直接使用Button组件就是正常的。启动都启动不了我也很费解

**Comment by arvinxx** [comment]
有仓库或者复现步骤吗

**Comment by arvinxx** [comment]
看了下是因为为了支持 ssr，antd-style 中依赖了 `emotion/server` 模块。这个模块依赖了 node相关的依赖 ：`buffer` 、`stream`。

而 cra 没有默认处理 node 相关的依赖。所以需要这样修改：

1. 安装相关依赖：

```bash
pnpm i buffer process react-app-rewired stream-browserify
```

2. 修改 `package.json` 的脚本为：

```json
{
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired  test",
    "eject": "react-scripts eject"
  },
}
```

3. 添加 `config-overrides.js` 文件，修改相关的 webpack 配置：

```js
const webpack = require("webpack");

module.exports = (config, env) => {
  config.resolve.fallback = Object.assign(config.resolve.fallback || {}, {
    stream: require.resolve("stream-browserify"),
  });

  config.plugins = (config.plugins || []).concat([
    new webpack.ProvidePlugin({
      process: "process/browser",
      Buffer: ["buffer", "Buffer"],
      stream: require.resolve("stream-browserify"),
    }),
  ]);
  return config;
};
```

**Comment by arvinxx** [comment]
另外建议后续创建应用不要再使用 cra 了，已经被 react 官方废弃了。使用 nextjs 吧
