### ISSUE TITLE
🧐[问题] vite中使用报错

### ISSUE THREAD

**Issue by mwj610** [ant-design/antd-style#38]
![image](https://user-images.githubusercontent.com/52907799/228154583-a1a60f75-f9a6-4297-b6f3-7d46e35f5787.png)

![image](https://user-images.githubusercontent.com/52907799/228154790-8f381b6c-c81b-4df0-a997-b142520b260b.png)

![image](https://user-images.githubusercontent.com/52907799/228154971-fedb7ba5-efd5-41b1-bfa3-80fd3186d32c.png)

**Comment by arvinxx** [comment]
vite 下没有 global 对象么？

**Comment by mwj610** [comment]
> vite 下没有 global 对象么？

不太清楚  没怎么用过

**Comment by arvinxx** [comment]
@mwj610 帮忙验证一下上述版本是否有效，感谢~

**Comment by mwj610** [comment]
> @mwj610 帮忙验证一下上述版本是否有效，感谢~


还是有点问题

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/52907799/228248817-149a0431-cf2c-4fa8-bccf-51c652804183.png">

<img width="413" alt="image" src="https://user-images.githubusercontent.com/52907799/228249034-887ce394-4b4a-48ed-85bb-95ef769d850a.png">

**Comment by arvinxx** [comment]
@mwj610 有没有可复现的 demo？

**Comment by mwj610** [comment]
> @mwj610 有没有可复现的 demo？

https://codesandbox.io/p/sandbox/cranky-pike-pmclp0?file=%2Fsrc%2Fmain.tsx&selection=%5B%7B%22endColumn%22%3A20%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A20%2C%22startLineNumber%22%3A9%7D%5D

**Comment by arvinxx** [comment]
@mwj610  上述 demo 已验证，应该修好了

**Comment by mwj610** [comment]
> @mwj610 上述 demo 已验证，应该修好了

嗯嗯，没问题了

**Comment by SCWR** [comment]
<StyleProvider /> 也有相同的问题

**Comment by arvinxx** [comment]
@SCWR  这个看不出来具体是啥原因哎

**Comment by SCWR** [comment]
> @SCWR 这个看不出来具体是啥原因哎

<img width="808" alt="image" src="https://github.com/ant-design/antd-style/assets/8925282/0d0f0597-3ee6-4df6-911e-47bf97aa2f62">
你要不要全项目搜索下  global ?

**Comment by SCWR** [comment]
@arvinxx 有空看看吗？

**Comment by arvinxx** [comment]
@SCWR ok

**Comment by arvinxx** [comment]
@SCWR 试试 3.5.1
