### ISSUE TITLE
👑 [需求] 提供全局的 cx 工具方法

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/antd-style#41]
### 🥰 需求描述

可以从全局导入 `cx` 方法：
```ts
import { cx } from 'antd-style'
```

### 场景

有些组件里面用到了全局的 `原子类` 但又不需要使用 `createStyles` 创建额外的样式

### 解决的问题
这样的话我就可以把 `classnames` 去掉让代码看着舒服一点

**Comment by arvinxx** [comment]
现在就有

**Comment by liuweiGL** [comment]
草率了，抱歉

**Comment by arvinxx** [comment]
没事，后面我们文档补充一下。现在的文档里没体现。
