### ISSUE TITLE
🐛[BUG] 官网 文档 和 使用案例 的链接是错误的

### ISSUE THREAD

**Issue by snoozemo** [ant-design/antd-style#45]
### 🐛 bug 描述
官网 `文档` 和 `使用案例` 的链接是错误的

![image](https://user-images.githubusercontent.com/76504395/232319751-9dc98d1c-ca2d-4ada-a95a-517093ff069f.png)

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/html2ksetch-demo-m53be?file=/src/Demo.tsx)

### © 版本信息

- antd-style 版本: [e.g. 1.0.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by arvinxx** [comment]
已修复，感谢反馈
