### ISSUE TITLE
👑 [需求] 支持 container 配置

### ISSUE THREAD

**Issue by IamFive** [ant-design/antd-style#46]
### 🥰 需求描述

支持使用 `antd` 的 `style-provider` , 让用户自由指定css的插入位置。

https://github.com/ant-design/cssinjs#styleprovider

### 🧐 解决方案

1. 支持使用 https://github.com/ant-design/cssinjs#styleprovider 的container属性

<html>
<body>

container | Tell cssinjs where to inject style in. | Element \| ShadowRoot | document.head
-- | -- | -- | --

2. emotion itself supports container too, so, explore the emotion API to user can fix this issue too.

</body>
</html>

**Comment by taiyangzaitianshang** [comment]
有个相似的问题，不知是不是用的不对。使用ant-style在基于 antd 二次封装的组件库时，使用了createInstance这个API，并使用这个API返回对象中的StyleProvider去指定container，但是没有生效
```
<StyleProvider container={document.body}>
      <MyComponent></MyComponent>
    </StyleProvider>
```

**Comment by arvinxx** [comment]
@IamFive  试试上面这个版本

**Comment by arvinxx** [comment]
好像是还有点问题，我再修下

**Comment by arvinxx** [comment]
与 #47 重复，合并到 #47 中讨论，这个先关了
