### ISSUE TITLE
🐛[BUG] createInstance创建的StyleProvider的props类型不对

### ISSUE THREAD

**Issue by basala** [ant-design/antd-style#50]
### 🐛 bug 描述

使用createInstance创建的styleProvider的props类型不对

### 📷 复现步骤
```
import { legacyLogicalPropertiesTransformer } from "@ant-design/cssinjs";

<StyleProvider transformers={[legacyLogicalPropertiesTransformer]}}></StyleProvider>
```
transformers提示类型不匹配
<img width="898" alt="image" src="https://github.com/ant-design/antd-style/assets/26861977/e33bfdc0-f536-4124-a32f-330b2bd1eb2b">

### 🏞 期望结果
不会提示类型错误

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/beautiful-haze-2t0j2z?file=/src/Demo.tsx)

### © 版本信息

- antd-style 版本: [3.1.0]
- 浏览器环境 [Chrome]
- 开发环境 [mac OS]

### 🚑 其他信息

**Comment by basala** [comment]
<img width="722" alt="image" src="https://github.com/ant-design/antd-style/assets/26861977/94ea85cc-d536-4cc8-a7f3-d3df3ea1527c">
ant-design/cssinjs types路径是lib
<img width="953" alt="image" src="https://github.com/ant-design/antd-style/assets/26861977/9fadcf7f-33fe-4d09-89e5-d44fa188bc36">
这里是es
导致类型对不上了

**Comment by basala** [comment]
> > <img alt="image" width="722" src="https://user-images.githubusercontent.com/26861977/237600194-94ea85cc-d536-4cc8-a7f3-d3df3ea1527c.png">
> > ant-design/cssinjs types路径是lib <img alt="image" width="953" src="https://user-images.githubusercontent.com/26861977/237600379-9fadcf7f-33fe-4d09-89e5-d44fa188bc36.png"> 这里是es
> > 导致类型对不上了
> 
> antd 的 cssinjs 有导出这个Context的类型么？我记得好像是因为没导出，所以我引了es

看了下没导出，从antd的cssinjs import legacyLogicalPropertiesTransformer的时候路径是lib，应该是这个导致的对不上，
或者能不能改成用React.ComponentProps<typeof StyleProvider>获取下类型

**Comment by arvinxx** [comment]
> 从antd的cssinjs import legacyLogicalPropertiesTransformer的时候路径是lib

@basala 你改成从 es 引入呢？

**Comment by basala** [comment]
> > 从antd的cssinjs import legacyLogicalPropertiesTransformer的时候路径是lib
> 
> @basala 你改成从 es 引入呢？

<img width="920" alt="image" src="https://github.com/ant-design/antd-style/assets/26861977/e48eb92c-9715-480d-90a2-b82af77c2b40">
改成这样确实不报错了
但是ant-design/cssinjs默认导入路径是lib
<img width="818" alt="image" src="https://github.com/ant-design/antd-style/assets/26861977/8b6d01bb-10cd-4448-8d35-23a90e20f89f">

**Comment by arvinxx** [comment]
那感觉只要把包的前面那个 es 改成 lib 就好了？有没有兴趣来个 pr ？

**Comment by basala** [comment]
> 

🉑️我改了你看看

**Comment by basala** [comment]
> 那感觉只要把包的前面那个 es 改成 lib 就好了？有没有兴趣来个 pr ？

🉑️，我改了在麻烦大佬看看

**Comment by basala** [comment]
好像没有合并权限，麻烦大佬看下没问题的话帮忙合并发布一下～

**Comment by arvinxx** [comment]
@basala 来试试

**Comment by basala** [comment]
> @basala 来试试

可以了，感谢大佬
