### ISSUE TITLE
👑 [需求] 开放 context ，context 上增加 set 方法

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/antd-style#53]
### 🥰 需求描述
感觉可以 antd-style 开放 context ，context 上增加 set 方法
https://github.com/umijs/umi/discussions/11142#discussioncomment-5915192

**Comment by xiaohuoni** [comment]
@arvinxx cc

**Comment by arvinxx** [comment]
开放context是什么意思？加上 set 应该 OK

**Comment by arvinxx** [comment]
已补充 demo: https://ant-design.github.io/antd-style/guide/switch-theme#docs-guide-switch-theme-demo-globalswitch
