### ISSUE TITLE
🐛[BUG] useResponsive与createStyles中responsive断点大小不一致

### ISSUE THREAD

**Issue by mwj610** [ant-design/antd-style#55]
https://codesandbox.io/s/magical-keldysh-1cmt01?file=/App.tsx

![image](https://github.com/ant-design/antd-style/assets/52907799/aa100c93-db0e-4a8a-bd1a-7033d66733e5)

**Comment by arvinxx** [comment]
你指的不一致是指？

**Comment by mwj610** [comment]
> 
`useResponsive`中`tablet`是 768  
`createStyles`中`tablet`是 991

**Comment by arvinxx** [comment]
哦 这看起来是 demo 的演示问题。 useResponsive 和 createStyles 背后其实用的是同一套值；

**Comment by mwj610** [comment]
> 哦 这看起来是 demo 的演示问题。 useResponsive 和 createStyles 背后其实用的是同一套值；

这个值好像还是不对。🤔

https://codesandbox.io/s/magical-keldysh-1cmt01?file=/App.tsx

![image](https://github.com/ant-design/antd-style/assets/52907799/07f00c8c-b72e-4277-8ece-e02356ad3fc9)

**Comment by arvinxx** [comment]
你重新看下文档demo
