### ISSUE TITLE
🧐[问题] 怎么理解appearance和themeMode这两个属性的区别？

### ISSUE THREAD

**Issue by chj-damon** [ant-design/antd-style#60]
### 🧐 问题描述

我在实现明暗模式切换的时候，看文档里面`appearance`和`themeMode`这两个都可以做到，想问一下这两个属性是有什么区别吗？否则为什么要单独分开？

### 🚑 其他信息
https://ant-design.github.io/antd-style/guide/switch-theme

**Comment by chj-damon** [comment]
从表现上来看，当themeMode='dark'的时候，appearance也是dark； themeMode='auto'的时候，appearance=‘dark’ | 'light'， 那干嘛还需要appearance这个prop？

**Comment by arvinxx** [comment]
看下 #52
