### ISSUE TITLE
🐛[BUG] Erroneous type of ThemeProvider

### ISSUE THREAD

**Issue by alex-golubtsov** [ant-design/antd-style#63]
[This change](https://github.com/ant-design/antd-style/commit/8bd8e8c7fcefe6cfa192fd0082db1babd6539faa) breaks `ThemeProvider` rendering.

Demo:
<img width="865" alt="image" src="https://github.com/ant-design/antd-style/assets/1982853/4e224518-f862-4756-9eb4-0e855667ac87">

It makes perfect sense, since `ReactNode` cannot be returned by`React.FC`

**Comment by arvinxx** [comment]
Thanks for your issuing, could your please show me a codesandbox to debug it? I try with @types/react ^18,it seems work well.

**Comment by arvinxx** [comment]
if you check the types in [@types/react@18](https://unpkg.com/browse/@types/react@18.2.8/index.d.ts), you will see FunctionComponent ( alias of FC ) return ReactNode (Line 553).

antd-style 's peerDeps is:
```json
  "peerDependencies": {
    "react": ">=18"
  }
```

So I think it's not a bug.

**Comment by alex-golubtsov** [comment]
@arvinxx currently `@types/react` use [ts5.0 types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/package.json#L50). I don't understand why they do it even for ts versions < 5, but that's how it is. And [there](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/ts5.0/index.d.ts#L521) there is `ReactElement` instead of `ReactNode`.

Probably worth to investigate. Which version of `@types/react` do you rely on?

**Comment by arvinxx** [comment]
> Which version of @types/react do you rely on? Bet it's < 18.0.37

@alex-golubtsov  latest, 18.2.8: https://unpkg.com/browse/@types/react@18.2.8/index.d.ts

**Comment by alex-golubtsov** [comment]
> > Which version of @types/react do you rely on? Bet it's < 18.0.37
> 
> @alex-golubtsov latest, 18.2.8: https://unpkg.com/browse/@types/react@18.2.8/index.d.ts

@arvinxx thanks for the clarification! It finally works with typescript ^5
