### ISSUE TITLE
🧐[问题]如何通过antd-style去覆盖antd中message、modal等非根节点插入组件的样式

### ISSUE THREAD

**Issue by jsoyoy** [ant-design/antd-style#71]
### 🧐 问题描述

业务开发，基于antd的二次开发，message、modal需要重写样式，如何通过antd-style去进行样式覆盖呢？

**Comment by jsoyoy** [comment]
💻 示例代码

Them.tsx

<img width="838" alt="截屏2023-06-20 上午10 57 46" src="https://github.com/ant-design/antd-style/assets/12870807/c98bc1aa-b2c7-426f-a668-1ecd84114160">

index.tsx

<img width="811" alt="截屏2023-06-20 上午10 56 42 1" src="https://github.com/ant-design/antd-style/assets/12870807/115d2261-f5e8-4e35-a97a-b657271a51da">

效果图

<img width="1229" alt="截屏2023-06-20 上午11 14 34" src="https://github.com/ant-design/antd-style/assets/12870807/bf8e24c0-e93c-4b4e-ae6a-1051a555ca9c">

我现在的方案是通过ThemeProvider注入自定义的变量，然后在把需要覆写样式挂载到ThemWrapper这个包裹组件上。对应的Button这种组件能实现样式覆盖，但是对于message这种没有挂载到根节点的组件是不会生效的。请问有没有更好的方法去覆盖它的样式。

**Comment by arvinxx** [comment]
应该可以直接使用 ConfigProvider 的能力了。感觉可以不用放在 antd-style 里来做
<img width="904" alt="image" src="https://github.com/ant-design/antd-style/assets/28616219/624934de-10e9-487c-a691-78a25b0186b8">
