### ISSUE TITLE
🧐[问题] 迁移过程中 less语法中使用到的 :global 怎么处理

### ISSUE THREAD

**Issue by consistent-k** [ant-design/antd-style#72]
### 🧐 问题描述

迁移过程中 less语法中使用到的 :global 怎么处理，之前有部分场景需要通过:global 去覆盖组件样式，迁移过程中这部分代码如何处理。

### 💻 示例代码

:global(.ant-btn-link) {
     padding: 0px;
     font-size: 12px；
}

### 🚑 其他信息
antd4 & umi4

**Comment by arvinxx** [comment]
去掉就好了

**Comment by arvinxx** [comment]
另外可以使用 codemod 一键迁移：https://ant-design.github.io/antd-style/guide/migrate-less-codemod
