### ISSUE TITLE
🐛[BUG] Vscode报 “ThemeProvider”不能用作 JSX 组件 & 控制台报  Cannot read properties of undefined (reading 'useToken')

### ISSUE THREAD

**Issue by consistent-k** [ant-design/antd-style#73]
### 🐛 bug 描述

<img width="687" alt="image" src="https://github.com/ant-design/antd-style/assets/67736912/6b0d9a97-14cc-4f6c-a95b-363fe85e12d4">

![image](https://github.com/ant-design/antd-style/assets/67736912/879f7d65-34e3-498b-9839-804be8580e31)

### 💻 复现代码

```js
import { createStyles, ThemeProvider } from 'antd-style';

const useStyles = createStyles(({ stylish, cx, css, token }) => {
    return {
        btn: {
            color: 'red'
        }
    };
});


const App = () => {
    const { styles } = useStyles();
    return (
        <div className={styles.btn}>
            按钮
        </div>
    );
};
export default () => {
    return (
        <ThemeProvider>
            <App />
        </ThemeProvider>
    );
};
```

### © 版本信息

- antd-style 版本: 3.3.0
- 浏览器环境 chrome
- 开发环境 Macos

### 🚑 其他信息
umi4框架 & antd4

**Comment by consistent-k** [comment]
补充: 这个必须使用antd5呀。。 我是想在antd4的业务模块下使用这个，看来是做不到了吧。

**Comment by BrettKimmons** [comment]
ant5也报错
umimax
    "typescript": "4.9.5"
    "@umijs/max": "^4.0.76",
    "antd": "^5.4.0",
    "antd-style": "^3.4.4",
>

**Comment by arvinxx** [comment]
@BrettKimmons 给个复现demo
