### ISSUE TITLE
使用Provider以后就会渲染多次🐛[BUG]

### ISSUE THREAD

**Issue by RuffianLiu** [ant-design/antd-style#94]
没用使用的情况下：
![image](https://github.com/ant-design/antd-style/assets/72987542/8e2fe457-999f-4d12-bb99-12c73fb0c61b)
<img width="468" alt="1692113083341" src="https://github.com/ant-design/antd-style/assets/72987542/2b0e0581-cbb8-4fa6-af6a-2aed91087f54">
使用后：
![1692113225709](https://github.com/ant-design/antd-style/assets/72987542/c23c002b-158a-47bc-9304-b5ea2216d03c)
<img width="460" alt="1692113244147" src="https://github.com/ant-design/antd-style/assets/72987542/7537e0d8-94d7-4c07-85a2-301bfa271adf">

**Comment by arvinxx** [comment]
@RuffianLiu 啥原因？
