### ISSUE TITLE
🧐[问题]迁移过程中@media 怎么处理

### ISSUE THREAD

**Issue by luyuanx2** [ant-design/antd-style#95]
### 🚑 其他信息

![image](https://github.com/ant-design/antd-style/assets/26129033/1a0abe5d-4775-456e-b61a-f8a60f1d874d)

**Comment by luyuanx2** [comment]
@media块代码这么写没有生效，是我写的方式不对吗

**Comment by arvinxx** [comment]
'' 对于 ${} 不生效的呀，你要换成 ``

**Comment by luyuanx2** [comment]
> '' 对于 ${} 不生效的呀，你要换成 ``

换成这样就报错了
<img width="911" alt="image" src="https://github.com/ant-design/antd-style/assets/26129033/32a223bd-e4a8-4093-b6b4-e64aa23b1a89">

**Comment by arvinxx** [comment]
加中括号

[`...`]:

**Comment by luyuanx2** [comment]
> 加中括号
> 
> ```
> [`...`]:
> ```

可以了，多谢
