### ISSUE TITLE
🧐[问题] 如何获取组件的token呢？

### ISSUE THREAD

**Issue by Jveen-D** [ant-design/antd-style#96]
### 🧐 问题描述

我在写业务的时候为了遵循UI的规范，需要用到各个组件的`token`，例如`Upload`组件的`actionsColor`值我要如何获取，我并没有在`useTheme`或者在`createStyles`中找到它们，我要如何获取组件`token`.

### 💻 示例代码

```typescript
import { createStyles } from 'antd-style'
const useStyles = createStyles(({ cx, css, prefixCls, token, responsive }) => {
  console.log(
    '🚀 ~ file: styles.ts:3 ~ useStyles ~ token:',
    token.actionsColor
  )
 
  return {
    DesignScheduleDetail: css`
      height: calc(100vh - 64px);
      width: 100%;
      padding: 16px;
    `
  }
})
export default useStyles
```
获取不到组件`token`

**Comment by Jveen-D** [comment]
我现在的处理方式是查找[ant-design](https://github.com/ant-design/ant-design)的仓库，然后找到对应组件的某个token计算方法，然后粘贴到自己的项目中。

**Comment by arvinxx** [comment]
目前 antd-style 没有组件 token，后续应该也不会加组件 token。为啥你希望开发的组件使用组件 token 呢？理论上使用 map 就够用了

**Comment by Jveen-D** [comment]
> 目前 antd-style 没有组件 token，后续应该也不会加组件 token。为啥你希望开发的组件使用组件 token 呢？理论上使用 map 就够用了

举个项目中的例子，我需要把左边table的表头背景色给到右边甘特图的表头背景色。
![image](https://github.com/ant-design/antd-style/assets/46897216/e2960702-7cc6-4ec4-93e9-bd6e95d448c5)
现在唯一的操作方法就是翻仓库并拿到table表头背景色的计算规则，我这里使用的是
```typescript
const tableBg = new TinyColor(token.colorFillAlter)
    .onBackground(token.colorBgContainer)
    .toHexShortString()
```
---
文档上有组件`token`，但是没有通过`useTheme`和`createStyles`获取到。我还以为有其他的方式来获取组件`token`，拿不到组件`token`问题也不大，翻翻文档也没啥坏处。
