### ISSUE TITLE
'ThemeProvider' cannot be used as a JSX component.🐛[BUG]

### ISSUE THREAD

**Issue by distance321** [ant-design/antd-style#98]
### 🐛 bug 描述
组件库打包时会报错，'ThemeProvider' cannot be used as a JSX component.

### 📷 复现步骤
当package.json中的@typescript-eslint/eslint-plugin、@typescript-eslint/parser升到5以上时，组件库内使用ThemeProvider在打包时就会报错, 在4.x时没有这个问题。

### 💻 复现代码
![image](https://github.com/ant-design/antd-style/assets/42052968/a376fd93-898f-4596-a6bb-253d86e9a2f2)

### © 版本信息

- antd-style 版本: 3.4.4
- 浏览器环境 chrome
- 开发环境 mac OS

### 🚑 其他信息

![image](https://github.com/ant-design/antd-style/assets/42052968/93e58c98-390d-46ca-b7e2-e794c8151295)

**Comment by arvinxx** [comment]
为啥关了

**Comment by distance321** [comment]
发现并不是因为升级@typescript-eslint的问题 降版本后也不行

**Comment by distance321** [comment]
升级这些依赖可以解决这个问题      
`
"@types/react": "^18.0.10",
"@types/react-dom": "^18.0.5",
`
